### ISSUE TITLE
Question about intended usage

### ISSUE THREAD

**Issue by afeld** [Snowflake-Labs/roleout#2]
I stumbled across this repository and am curious about it. As someone unfamiliar with the tool, I think I get the idea based on the README, but it's a little unclear what the steps are.

- Is the idea that teams are using Roleout once, then working with the generated Terraform/SQL from there, or is it a tool we will be coming back to regularly?
- Is the YAML meant to be interacted with directly, or only through the GUI?

Thanks!

**Comment by sfc-gh-ckite** [comment]
Hi @afeld, thanks for the questions.

1) Roleout is mostly targeted at teams starting a new Snowflake account from scratch. After you design your environment with Roleout and deploy with Terraform, you would likely come back overtime and continue to add/change objects in Roleout, and deploy the new Terraform.
2) While the primary mode of interaction with Roleout is the GUI, the yaml is also intended to be human readable/editable. I would say it would be more likely to programmatically modify the yaml, e.g. if you had a very large number of schemas/virtual warehouses you could put those in the yaml and let Roleout generate Terraform.
